### ISSUE TITLE
FBInk.fbink_print_ot(fbfd, b + s.c_str(), fbink_ot_cfg, fbink_cfg, ffi.NULL)

### ISSUE THREAD

**Issue by a442509097** [NiLuJe/py-fbink#1]
```
def printString(s):
            FBInk.fbink_print_ot(fbfd, b + s.c_str(), fbink_ot_cfg, fbink_cfg, ffi.NULL)
```
what does b mean and how to make it work?

**Comment by a442509097** [comment]
ok, is bytes type.
```
temp = bytes("123", encoding='utf-8')
FBInk.fbink_print_ot(fbfd, temp, fbink_ot_cfg, fbink_cfg, ffi.NULL)
```

**Comment by NiLuJe** [comment]
Context would have been helpful, as I have no idea where this code is from ;).

And, yes, it's a [`const char*`](https://github.com/NiLuJe/FBInk/blob/6572b5f393f810785e382104391d177120da46f6/fbink.h#L777-L781), which makes that a `bytes` object on [Python 3](https://github.com/NiLuJe/py-fbink/blob/d41523291fa8a5de2570749cf1f61135c7039b4f/hello.py#L46-L47).
